- repo: https://github.com/pre-commit/pre-commit-hooks.git
  sha: v0.7.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: autopep8-wrapper
  - id: check-docstring-first
  - id: double-quote-string-fixer
  - id: check-json
  - id: debug-statements
  - id: name-tests-test
  - id: requirements-txt-fixer
  - id: flake8
- repo: https://github.com/pre-commit/pre-commit.git
  sha: v0.12.0
  hooks:
  - id: validate_config
  - id: validate_manifest
- repo: https://github.com/asottile/reorder_python_imports.git
  sha: v0.3.1
  hooks:
  - id: reorder-python-imports
